### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by sgiulianiamius** [poychang/Message-Card-Model#2]
Hello,
I am using your package, I like it a lot!
Are you aware if there is a way to create tables or table-like structure with MessageCard(s).
Thanks

**Comment by poychang** [comment]
You can use `Section.Facts` to do 2 columns table.
For more columns, MassageCard do not support. You have to use `AdaptiveColumn` from [AdaptiveCards](https://www.nuget.org/packages/AdaptiveCards/).
Thanks for your comment. 😀

**Comment by sgiulianiamius** [comment]
Hey hello, thanks for the prompt response.

Yesterday night I realised that is possible to create HTML tables and send them down with Message Card(s).

You can try it with powershell yourself:
`Invoke-RestMethod -Method post -ContentType 'Application/Json' -Body '{"summary": "XXXX", "sections": [ { "startGroup": true, "text": "<table><tr><td>asd</td><td>asd</td><td>asd</td></tr><tr><td>asd</td><td>asd</td><td>asd</td></tr></table>" } ]}' -Uri <URL>`

**Comment by poychang** [comment]
According [official guideline](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#design-guidelines), they do not support html tag in card...
But it's nice that is works in your code 😀

**Comment by sgiulianiamius** [comment]
never trust msft guides! :-)
