### ISSUE TITLE
.ToJson() method outputs incorrectly cased output for TargetOs.Default

### ISSUE THREAD

**Issue by LeeSalter** [poychang/Message-Card-Model#6]
Hi there,

The following code outputs incorrect JSON for Teams by uppercasing the first letter of Default for the TargetOs. It should output default with a lower case d in order for the button to correctly appear in Teams.

`var card = new MessageCard
                {
                    Title = "Title here",
                    Text = "Text here",
                    ThemeColor="ff0000",
                    Context="https://schema.org/extensions",
                    Type="MessageCard",
                    Actions = new[]
                    {
                       new OpenUriAction
                       {
                           Name="Open Website",
                           Type=ActionType.OpenUri,
                           Targets=new List<Target>
                           {
                               new Target
                               {
                                   OS=TargetOs.Default,
                                   Uri="https://a.good.site/"
                               }
                           }
                       }
                   }
                };`

Validated with Insomnia.

**Comment by poychang** [comment]
Thanks for the report. It will be fixed in the next version.

**Comment by poychang** [comment]
Thanks for the report. It will be fixed in the next version.
Close this issue. Feel free to reopen it if it breaks again.
