### ISSUE TITLE
[Feature request] Add support for mention users in teams

### ISSUE THREAD

**Issue by abdushaj** [poychang/Message-Card-Model#7]
Just curious if the feature for mentioning users in cards will be supported. 

`"msteams": {
            "entities": [
                {
                    "type": "mention",
                    "text": "<at>Adele UPN</at>",
                    "mentioned": {
                      "id": "AdeleV@contoso.onmicrosoft.com",
                      "name": "Adele Vance"
                    }
                  },
                  {
                    "type": "mention",
                    "text": "<at>Adele AAD</at>",
                    "mentioned": {
                      "id": "87d349ed-44d7-43e1-9a83-5f2406dee5bd",
                      "name": "Adele Vance"
                    }
                  }
            ]
        }`

**Comment by poychang** [comment]
MessageCard is not support Teams Mention. You need to use AdativeCard. [Here](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#user-mention-in-incoming-webhook-with-adaptive-cards?WT.mc_id=DT-MVP-5003022) is the docs.
